[package]
name = "glop"
version = "0.1.0"
edition = "2021"
license = "Zlib"
default-run = "glop"

[dependencies]
colored = "2.0.0"
fasmg-ebc-rs = { git = "https://github.com/Pebaz/fasmg-ebc-rs" }
logos = "0.12.0"
indextree = "4.3.1"
