[package]
name = "glop"
version = "0.1.0"
edition = "2021"
license = "Zlib"
default-run = "glop"

[dependencies]
colored = "*"
fasmg-ebc-rs = { git = "https://github.com/Pebaz/fasmg-ebc-rs" }
logos = "*"
